name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: yarn install
      #   run: yarn install
      # - name: gatsby build
      #   env:
      #     GH_API_KEY: ${{ secrets.GITHUB_API_KEY }}
      #   run: yarn build
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GITHUB_API_KEY }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
